### ISSUE TITLE
Support Ansible Vault

### ISSUE THREAD

**Issue by vkrizan** [ansible/event-driven-ansible#115]
Hello,

Please add support for [Ansible Vault](https://docs.ansible.com/ansible/latest/vault_guide/vault_using_encrypted_content.html).

```
- name: secrets example
  hosts: all
  sources:
    - ansible.eda.webhook:
        token: "{{ SECRET }}"
```
```
$ ansible-rulebook --rulebook secrets-example.yml -i inventory.yml -e @secrets_file.enc  --verbose
```

Thank you.
