### ISSUE TITLE
Cannot create Rulebook Activations as disabled 

### ISSUE THREAD

**Issue by zjleblanc** [ansible/event-driven-ansible#365]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that event-driven-ansible collection is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Using the rulebook_activation module, one cannot create resource in the disabled state. It will always be created as enabled.

### Environment

[de-support-rhel9:1.1.1-31](https://catalog.redhat.com/software/containers/ansible-automation-platform-25/de-supported-rhel9/650a5674ad524b664b693729)

ansible-rulebook-1.1.1-1.el9ap.noarch

### Steps to reproduce

Define a rulebook_activiation in configuration-as-code variables for use with infra.aap_configuration
```
---
eda_rulebook_activations:
  - name: Demo Rulebook Activation
    description: Rulebook that processes various events sourced from Dynatrace problems
    organization: Default
    project: EDA Demos
    rulebook: dynatrace_event_stream.yml
    decision_environment: Default Decision Environment
    event_streams: 
      - event_stream: Dynatrace Event Stream
        source_name: Dynatrace Event Source
    eda_credentials:
      - My Controller
    enabled: false
```
Ensure the variables file is loaded
Run a playbook and invoke `infra.aap_configuration.dispatch`

### Actual results

Rulebook activation **Demo Rulebook Activation** is created in the enabled state

### Expected results

Rulebook activation **Demo Rulebook Activation** is created in the disabled state
