### ISSUE TITLE
Create role_user_assignment and role_team_assignment modules

### ISSUE THREAD

**Issue by Tompage1994** [ansible/event-driven-ansible#407]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [x] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [x] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

At present there is no way to manage the role_user_assignment and role_team_assignment endpoints on the EDA Controller using this collection. The same modules exist in ansible.platform (for the gateway parts) and ansible.controller (for the controller parts) but not in ansible.eda

### Steps to reproduce

In the same way that you can with the other modules I expect to be able to use code like:

```
- ansible.eda.role_user_assignment:
        user: testuser1
        role_definition: Organization Eda Credential Admin
        object_id: 3
        state: present
```

### Current results

N/A missing feature which can't be managed through the ansible.platform collection module

### Suggested feature result

Work in the same way as `ansible.controller.role_user_assignment` and `ansible.controller.role_team_assignment`.

### Additional information

I have already put together some code for this and I reckon I'm at least 90% of the way there. I'll raise a PR for this immediately
