### ISSUE TITLE
Unable to build on ee minimal rhel9

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/event-driven-ansible#424]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [x] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [x] I understand that event-driven-ansible collection is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Get the following error when trying to include on rhel9 for an ansible excecution environment. 

```
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
  [end of output]
```

As a result if I do the following

When I include as a depenency 
dependencies:
  system:
    - pkg-config [platform:rpm]

I get the following 
```
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
 error: subprocess-exited-with-error
 × Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [12 lines of output]
      Cannot find libsystemd or libsystemd-journal:
```

I suspect the problem is https://github.com/ansible/event-driven-ansible/blob/main/requirements.txt
Contains requirements for both EDA AND the collection, and with the python included on the rhel9 minimal something is incompatible. 

### Environment

/python3.11
      registry.gitlab.com/ansible-community/execution-environments/ansible-automation-platform-images/aap25-ee-minimal-rhel9:latest

### Steps to reproduce

Run ansible builder. 
with the following EE definition
```
---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'
options:
  package_manager_path: /usr/bin/microdnf


dependencies:
  system:
    - pkg-config [platform:rpm]
  galaxy:
    collections:
      - name: ansible.eda
images:
  base_image:
    name: >-
      registry.gitlab.com/tmobile/ansible-community/execution-environments/ansible-automation-platform-images/aap25-ee-minimal-rhel9:latest

```

### Actual results

it fails to build the container.

### Expected results

it builds an EE with the collection installed.

**Comment by mkanoor** [comment]
@sean-m-sullivan Is this an EE issue or a DE issue?

**Comment by sean-m-sullivan** [comment]
Execution environment for including the eda ansible playbook collection

**Comment by Alex-Izquierdo** [comment]
Hi @sean-m-sullivan 
[libsystemd0 and libsystemd-dev are required](https://github.com/ansible/event-driven-ansible/blob/main/bindep.txt#L3) by one of eda plugins. Adding those system dependencies should solve the issue.

**Comment by sean-m-sullivan** [comment]
@Alex-Izquierdo  I tried Tried again
```
---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'
options:
  package_manager_path: /usr/bin/microdnf


dependencies:
  system:
    - pkg-config [platform:rpm]
    - libsystemd0 [platform:rpm]
    - libsystemd-dev [platform:rpm]
    - pkg-config  [platform:rpm]
  galaxy:
    collections:
      - name: ansible.eda
images:
  base_image:
    name: >-
      registry.gitlab.com//ansible-community/execution-environments/ansible-automation-platform-images/aap25-ee-minimal-rhel9:latest
```

The point of the requirement files are that the customer/user shouldn't have to play wack-a-mole with packages, ansible-builder should be able to pick things up from the requirement file. 

The other point was that the Event source requiremetns do not equal the EE reuirements, That the plugins for the decision environment are not the same as the execution environment. 

Also why are we building on debian when decision and execution environments are built on rhel/ubi

**Comment by Alex-Izquierdo** [comment]
Hi @sean-m-sullivan As far as I understand, requirements can not handle system dependencies, which is the case. That's why we already have it defined in the bindep file. 

Since the upstream DE used so far is the one [stored in quay](https://quay.io/repository/ansible/ansible-rulebook?tab=tags&tag=latest) from ansible-rulebook project (which is built from centos stream) and current Red Hat DE images already contains the collection as well as the supported EE image, I think simply nobody noticed this issue yet. So, unless I missing something else, I would say the only thing needed would be adding those dependencies in the bindep for the rpm platform so you don't need to add them explicitly in the builder spec. 

FYI, we have the plan to move out to a community collection the plugin "journald" which is what requires systemd-python and causing the issue.

**Comment by sean-m-sullivan** [comment]
@Alex-Izquierdo We are talking about two seperate things
one is required by the decision environment for EDA
One is required by the Execution environment for the controller
And it looks like they are incompatible, Thinking this makes argument for splitting them out, looking into possible solutions in the meantime.

**Comment by Alex-Izquierdo** [comment]
Sorry, what is incompatible? The mentioned libsystemd0 and libsystemd-dev libraries are required by the collection, regardless of if it is going to be installed in a EE or in a DE. 
Are you saying that declaring those system dependencies does not solve the problem? In that case can you provide the output? There might be other systemd dependencies for aap25-ee-minimal-rhel9 not identified yet.

**Comment by ansiblejunky** [comment]
I'm hitting this issue too right now with a customer and still haven't found a way to include the `eda` collection because of its complicated deps. Adding the collection to the dependencies for building an EE I get the following error.  It shouldn't be this difficult for customers to prepare and package an EE with the set of AAP config collections we offer. Just to note, I'm able to successfully build an EE without the `eda` collection - nice and clean.  However, adding the `eda` collection causes the below problem of which I cannot find a clean answer. This is on RHEL9 server, but using the rhel8 minimal EE base image... btw, same problem with the rhel9 minimal base image.  This is NOT an EE problem but simply a problem with the `requirements.txt` in the `eda` collection. It's definitely needing some updates or changes so that customers don't hit these frustrating problems.

```
Collecting systemd-python
  Downloading systemd-python-235.tar.gz (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-efdz1jk1/systemd-python_d30734b9c2c3457d9532e3714a8a8b8c/setup.py", line 55, in <module>
          **lib('libsystemd', 'libsystemd-journal', **defines))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-efdz1jk1/systemd-python_d30734b9c2c3457d9532e3714a8a8b8c/setup.py", line 40, in lib
          status, result = pkgconfig(name, **kw)
                           ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-efdz1jk1/systemd-python_d30734b9c2c3457d9532e3714a8a8b8c/setup.py", line 18, in pkgconfig
          status, result = call(pkgconf, '--libs', '--cflags', package)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-efdz1jk1/systemd-python_d30734b9c2c3457d9532e3714a8a8b8c/setup.py", line 6, in call
          cmd = Popen(cmd,
                ^^^^^^^^^^
        File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib64/python3.11/subprocess.py", line 1955, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by sean-m-sullivan** [comment]
@Alex-Izquierdo 
```
Sorry, what is incompatible? The mentioned libsystemd0 and libsystemd-dev libraries are required by the collection, regardless of if it is going to be installed in a EE or in a DE.
```
Can you point to which of these plugins require that, I'm not seeing it

https://github.com/ansible/event-driven-ansible/tree/main/plugins

I am running the following for definition
```
---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'
options:
  package_manager_path: /usr/bin/microdnf


dependencies:
  system:
    - wget
    - iputils
  python:
    - pkgconfig
    - libsystemd0
  exclude:
    python: 
      - cryptography
  galaxy:
    collections:
      - name: ansible.utils
      - name: community.general
      - name: ansible.platform
      - name: ansible.hub
      - name: ansible.controller
      - name: ansible.eda
      - name: infra.aap_configuration

additional_build_steps:
  prepend_base:
    RUN $PYCMD -m pip install --upgrade pip

  append_final: |
    RUN pip install ansible-lint --ignore-installed

images:
  base_image:
    name: >-
      registry.gitlab.com/ansible-community/execution-environments/ansible-automation-platform-images/aap25-ee-minimal-rhel8:latest
```

**Comment by Alex-Izquierdo** [comment]
@sean-m-sullivan the plugin that requires the systemd stuff is https://github.com/ansible/event-driven-ansible/blob/main/extensions/eda/plugins/event_source/journald.py

I would have to take time to try to install the collection in aap25-ee-minimal-rhel8:latest, pretty sure there is some system dependency missing. I think we never tried that yet. 

I wonder also if @jamesmarshall24 or @simaishi can provide some tip. They worked on the DE and maybe they already know what we are missing.

**Comment by sean-m-sullivan** [comment]
My point is that is a dee event driven plug-in, not an ee ansible-core module, as those are two different systems not sure why it's giving such a hard time on these

**Comment by Alex-Izquierdo** [comment]
@sean-m-sullivan @ansiblejunky 
For rhel8 at least, it seems there are no precompiled wheels for python-systemd so it tries to compile it. 
You need `systemd-devel gcc python3.11-devel pkg-config` system packages, then requirements.txt don't fail.

**Comment by ptoscano** [comment]
> You should not add those system dependencies as they will go into the final image. Add them, instead, to the builder image, like this:

There is no need to manually install them; rather, annotate then as `compile`, so `ansible-builder` installs them only in the build stages. See the `ansible-builder` documentation:
https://docs.ansible.com/projects/builder/en/latest/collection_metadata/#system-level-dependencies

So to edit a bit part of the example of @djdanielsson:
```yaml
dependencies:
  system:
    - gcc [compile platform:rpm]
    - systemd-devel [compile platform:rpm]
    - python3.11-devel [compile platform:rpm]
```

**Comment by ptoscano** [comment]
I just merged #533, which fixes almost all the issues in the existing `bindep.txt`; there will be a new version of the collection containing also this change in few days.

I say "almost" because you will still need to specify the Python development package: since the actual version depends on the base image or the installed Python, it cannot be specified within the collection itself (which works with multiple Python versions). Hence you will still need:
```yaml
dependencies:
  system:
    - python3.12-devel [compile platform:rpm]
```
(or whatever is the Python version in use)
